"""update field nidn unique tabel dosen

Revision ID: ed473a007833
Revises: dfc979d89add
Create Date: 2022-04-12 12:57:56.371339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed473a007833'
down_revision = 'dfc979d89add'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'dosen', ['nidn'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'dosen', type_='unique')
    # ### end Alembic commands ###
